In [ ]:
%%pyspark


dfa = spark.read.option("header", "true").csv("Files/Raw Data/Athletes.csv")
# remove unwanted spaces from column names
dfa = dfa.toDF(*[col.replace(" ", "") for col in dfa.columns])

dfc = spark.read.option("header", "true").csv("Files/Raw Data/Coaches.csv")
# remove unwanted spaces from column names
dfc = dfc.toDF(*[col.replace(" ", "") for col in dfc.columns])

dfe = spark.read.option("header", "true").csv("Files/Raw Data/EntriesGender.csv")
# remove unwanted spaces from column names
dfe = dfe.toDF(*[col.replace(" ", "") for col in dfe.columns])

dfm = spark.read.option("header", "true").csv("Files/Raw Data/Medals.csv")
# remove unwanted spaces from column names
dfm = dfm.toDF(*[col.replace(" ", "") for col in dfm.columns])

dft = spark.read.option("header", "true").csv("Files/Raw Data/Teams.csv")
# remove unwanted spaces from column names
dft = dft.toDF(*[col.replace(" ", "") for col in dft.columns])


# create temp table in order to be able to use them in sql
dfa.write.mode("overwrite").saveAsTable("Bronze.temp_athletes")
dfc.write.mode("overwrite").saveAsTable("Bronze.temp_coaches")
dfe.write.mode("overwrite").saveAsTable("Bronze.temp_entriesGender")
dfm.write.mode("overwrite").saveAsTable("Bronze.temp_medals")
dft.write.mode("overwrite").saveAsTable("Bronze.temp_teams");

StatementMeta(, 4929b4b6-4439-4a2f-8bb1-392874e54f65, 3, Finished, Available, Finished)

In [1]:
%%sql

-------------------------------------------------
-- Create Table AND Insert Data As Is From csv --
-------------------------------------------------

DROP TABLE IF EXISTS Bronze.athletes;

CREATE TABLE Bronze.athletes 
AS
SELECT *
FROM Bronze.temp_athletes;


DROP TABLE IF EXISTS Bronze.coaches;

CREATE TABLE Bronze.coaches 
AS
SELECT *
FROM Bronze.temp_coaches;


DROP TABLE IF EXISTS Bronze.entriesGender;

CREATE TABLE Bronze.entriesGender 
AS
SELECT *
FROM Bronze.temp_entriesGender;


DROP TABLE IF EXISTS Bronze.medals;

CREATE TABLE Bronze.medals 
AS
SELECT *
FROM Bronze.temp_medals;


DROP TABLE IF EXISTS Bronze.teams;

CREATE TABLE Bronze.teams 
AS
SELECT *
FROM Bronze.temp_teams;

StatementMeta(, e3ee09ce-dbac-4e22-a352-2a7939801072, 2, Finished, Available, Finished)

In [ ]:
%%sql 

DROP TABLE IF EXISTS Bronze.temp_athletes;
DROP TABLE IF EXISTS Bronze.temp_coaches;
DROP TABLE IF EXISTS Bronze.temp_entriesGender;
DROP TABLE IF EXISTS Bronze.temp_medals;
DROP TABLE IF EXISTS Bronze.temp_teams;

StatementMeta(, 4929b4b6-4439-4a2f-8bb1-392874e54f65, 18, Finished, Available, Finished)