In [2]:
%%sql

------------------------------------
-- Create Silver Table Structures --
------------------------------------

DROP TABLE IF EXISTS Silver.athletes;

CREATE TABLE Silver.athletes (
    athlete_id INT,
    athlete_name STRING,
    country STRING,
    discipline STRING
);


DROP TABLE IF EXISTS Silver.coaches;

CREATE TABLE Silver.coaches (
    coach_id INT,
    coach_name STRING,
    country STRING,
    discipline STRING,
    event STRING
);


DROP TABLE IF EXISTS Silver.teams;

CREATE TABLE Silver.teams (
    team_id INT,
    team_name STRING,
    discipline STRING,
    country STRING,
    event STRING
);


DROP TABLE IF EXISTS Silver.entries_gender;

CREATE TABLE Silver.entries_gender (
    entry_id INT,
    discipline STRING,
    female INT,
    male INT,
    total INT
);


DROP TABLE IF EXISTS Silver.medals;

CREATE TABLE Silver.medals (
    medal_id INT,
    rank INT,
    team_country STRING,
    gold_medals INT,
    silver_medals INT,
    bronze_medals INT,
    total_medals INT,
    rank_by_total INT
);

StatementMeta(, 7cc030a7-0718-4394-8e56-d665516b5b19, 11, Finished, Available, Finished)